clc;clear all;close all;
%run params.m;
%
addpath('../../utils/');
addpath('../');
data1 = load('../data/data11_1_1.mat');
data2 = load('../data/data11_1_2.mat');
data3 = load('../data/data11_1_3.mat');

[f_code1,t1,i_in_u1_1,i_in_u1_2,i_out_x1,i_out_dx1,i_out_f1]=extract_signals4identification(data1);
[f_code2,t2,i_in_u2_1,i_in_u2_2,i_out_x2,i_out_dx2,i_out_f2]=extract_signals4identification(data2);
[f_code3,t3,i_in_u3_1,i_in_u3_2,i_out_x3,i_out_dx3,i_out_f3]=extract_signals4identification(data3);

clear data1 data2 data3

nn_u1_1 = nn_refactor(i_in_u1_1);
nn_u2_1 = nn_refactor(i_in_u2_1);
nn_u3_1 = nn_refactor(i_in_u3_1);

nn_u1_2 = nn_refactor(i_in_u1_2);
nn_u2_2 = nn_refactor(i_in_u2_2);
nn_u3_2 = nn_refactor(i_in_u3_2);

nn_x1 = nn_refactor(i_out_x1);
nn_x2 = nn_refactor(i_out_x2);
nn_x3 = nn_refactor(i_out_x3);

nn_dx1 = nn_refactor(i_out_dx1);
nn_dx2 = nn_refactor(i_out_dx2);
nn_dx3 = nn_refactor(i_out_dx3);

nn_f1 = nn_refactor(i_out_f1);
nn_f2 = nn_refactor(i_out_f2);
nn_f3 = nn_refactor(i_out_f3);

nn_u = [nn_u1_1 nn_u2_1 nn_u3_1];
nn_x = [nn_x1 nn_x2 nn_x3];
nn_dx = [nn_dx1 nn_dx2 nn_dx3];
nn_f = [nn_f1 nn_f2 nn_f3];

mimo_u = [nn_u1_1; nn_u2_1; nn_u3_1];
mimo_T = [nn_x1 preprocess_dx(nn_dx1) nn_f1;
          nn_x2 preprocess_dx(nn_dx2) nn_f2;
          nn_x3 preprocess_dx(nn_dx3) nn_f3;];
t = t1;
X = mimo_u';
T = mimo_T';

%%
[X, ~] = tonndata(X, 1, 0);
[T, ~] = tonndata(T, 1, 0);
%%
net = narxnet();
[Xs, Xi, Ai, Ts] = preparets(net, X, {}, T);
net = train(net, Xs, Ts, Xi, Ai);
view(net);
Yopen = net(Xs, Xi, Ai);

net = closeloop(net);
view(net);
[Xs, Xi, Ai, Ts] = preparets(net, X, {}, T);
net = train(net, Xs, Ts, Xi, Ai);
Yclosed = net(Xs, Xi, Ai);

%Plot output with predicted output
%--------------------------------------------------------------------------

Yopen=cell2mat(Yopen);
Yclosed=cell2mat(Yclosed);
figure;
t = t(3:end);
T = T(3:end);
T=cell2mat(T);
%%
plot(t,T(1,:),'b-',t,Yopen(1,:),'r--',t,Yclosed(1,:),'k-.'); xlabel('Time (sec)');  ylabel('DSP1');
legend('Actual','Predicted (openloop)','Predicted (closedloop)');

figure;

plot(t,T(2,:),'b-',t,Yopen(2,:),'r--',t,Yclosed(2,:),'k-.'); xlabel('Time (sec)');  ylabel('DSP1');
legend('Actual','Predicted (openloop)','Predicted (closedloop)');

figure;

plot(t,T(3,:),'b-',t,Yopen(3,:),'r--',t,Yclosed(3,:),'k-.'); xlabel('Time (sec)');  ylabel('DSP1');
legend('Actual','Predicted (openloop)','Predicted (closedloop)');


function data = nn_refactor(data)
    data = data(:,2);
end

function y = preprocess_dx(x)
%  Preprocess input x
%    This function expects an input vector x.

% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 06-Apr-2021 17:29:19

y = lowpass(x,0.2,'Steepness',0.85,'StopbandAttenuation',60);
end
