function [datastore] = sb_pressure(datastore, flag)

    if flag == "init"
        datastore.DataVariables = ["AirPressure"; ...
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                        ];

        datastore.SelectedVariables = ["Label"; ...
                                       "AirPressure"; ...
                                       ];

    elseif flag == "signals"
        datastore.DataVariables = ["AirPressure"; ...
                                   "AirPressure_preproces"; ...
                                   "AirPressure_preproces_ps"; ...
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                        ];

        datastore.SelectedVariables = ["Label"; ...
                                       "AirPressure"; ...
                                       "AirPressure_preproces"; ...
                                       "AirPressure_preproces_ps"; ...
                                       ];

    elseif flag == "features"
        datastore.DataVariables = [
                                   "AirPressure_stats"; ...
                                   "AirPressure_preproces_stats"; ...
                                   "AirPressure_preproces_ps_spec"; ...
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                        ];

        datastore.SelectedVariables = ["Label"; ...
                                       "AirPressure_stats"; ...
                                       "AirPressure_preproces_stats"; ...
                                       "AirPressure_preproces_ps_spec"; ...
                                       ];

    elseif flag == "featuretable"
        featuretable = load('pressure_features.mat');
        datastore = featuretable;

    elseif flag == "both"
        datastore.DataVariables = ["AirPressure"; ...
                                   "AirPressure_stats"; ...
                                   "AirPressure_preproces"; ...
                                   "AirPressure_preproces_stats"; ...
                                   "AirPressure_preproces_ps"; ...
                                   "AirPressure_preproces_ps_spec"; ...
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                        ];

        datastore.SelectedVariables = ["Label"; ...
                                       "AirPressure"; ...
                                       "AirPressure_stats"; ...
                                       "AirPressure_preproces"; ...
                                       "AirPressure_preproces_stats"; ...
                                       "AirPressure_preproces_ps"; ...
                                       "AirPressure_preproces_ps_spec"; ...
                                       ];

    else
        disp("Add parameter flag = signals, features, both, featuretable \n return datastore, but if featuretable is set return will be featuretable");
    end
    datastore.IndependentVariables = [
                                    "ThrottleValve1"; ...
                                    "ThrottleValve2"; ...
                                    "SmallDamper_upper"; ...
                                    "LargeDamper_upper"; ...
                                    "SmallDamper_bottom"; ...
                                    "LargeDamper_bottom";
                                    "Settings.Load"];

end
