function [datastore] = sb_acc(datastore, flag)
    if flag == "init"
        datastore.DataVariables = [
                                   "AccelerometerMoving_axisY"; ...
                                   "AccelerometerMoving_axisZ"; ...
                                   "AccelerometerStatic_axisY"; ...
                                   "AccelerometerStatic_axisZ"; ...                         
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                       ];


        datastore.SelectedVariables = ["Label"; ...
                                   "AccelerometerMoving_axisY"; ...
                                   "AccelerometerMoving_axisZ"; ...
                                   "AccelerometerStatic_axisY"; ...
                                   "AccelerometerStatic_axisZ"; ...                         
                                        ];
    elseif flag == "signals"
        datastore.DataVariables = [
                                   "AccelerometerMoving_axisY"; ...
                                   "AccelerometerMoving_axisZ"; ...
                                   "AccelerometerStatic_axisY"; ...
                                   "AccelerometerStatic_axisZ"; ...                         
                                   "AccelerometerMoving_axisY_ps"; ...
                                   "AccelerometerMoving_axisZ_ps"; ...
                                   "AccelerometerStatic_axisY_ps"; ...
                                   "AccelerometerStatic_axisZ_ps"; ...                         
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                       ];


        datastore.SelectedVariables = ["Label"; ...
                                   "AccelerometerMoving_axisY"; ...
                                   "AccelerometerMoving_axisZ"; ...
                                   "AccelerometerStatic_axisY"; ...
                                   "AccelerometerStatic_axisZ"; ...                         
                                   "AccelerometerMoving_axisY_ps"; ...
                                   "AccelerometerMoving_axisZ_ps"; ...
                                   "AccelerometerStatic_axisY_ps"; ...
                                   "AccelerometerStatic_axisZ_ps"; ...                         
                                        ];

    elseif flag == "features"
        datastore.DataVariables = [
                                   "AccelerometerMoving_axisY_stats"; ...
                                   "AccelerometerMoving_axisZ_stats"; ...
                                   "AccelerometerStatic_axisY_stats"; ...
                                   "AccelerometerStatic_axisZ_stats"; ...                         
                                   "AccelerometerMoving_axisY_ps_spec"; ...
                                   "AccelerometerMoving_axisZ_ps_spec"; ...
                                   "AccelerometerStatic_axisY_ps_spec"; ...
                                   "AccelerometerStatic_axisZ_ps_spec"; ...                         
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                       ];


        datastore.SelectedVariables = ["Label"; ...
                                   "AccelerometerMoving_axisY_stats"; ...
                                   "AccelerometerMoving_axisZ_stats"; ...
                                   "AccelerometerStatic_axisY_stats"; ...
                                   "AccelerometerStatic_axisZ_stats"; ...                         
                                   "AccelerometerMoving_axisY_ps_spec"; ...
                                   "AccelerometerMoving_axisZ_ps_spec"; ...
                                   "AccelerometerStatic_axisY_ps_spec"; ...
                                   "AccelerometerStatic_axisZ_ps_spec"; ...                         
                                        ];

    elseif flag == "featuretable"
        featuretable = load('acc_features.mat');
        datastore = featuretable;

    elseif flag == "both"
        datastore.DataVariables = [
                                   "AccelerometerMoving_axisY"; ...
                                   "AccelerometerMoving_axisZ"; ...
                                   "AccelerometerStatic_axisY"; ...
                                   "AccelerometerStatic_axisZ"; ...                         
                                   "AccelerometerMoving_axisY_ps"; ...
                                   "AccelerometerMoving_axisZ_ps"; ...
                                   "AccelerometerStatic_axisY_ps"; ...
                                   "AccelerometerStatic_axisZ_ps"; ...                         
                                   "AccelerometerMoving_axisY_stats"; ...
                                   "AccelerometerMoving_axisZ_stats"; ...
                                   "AccelerometerStatic_axisY_stats"; ...
                                   "AccelerometerStatic_axisZ_stats"; ...                         
                                   "AccelerometerMoving_axisY_ps_spec"; ...
                                   "AccelerometerMoving_axisZ_ps_spec"; ...
                                   "AccelerometerStatic_axisY_ps_spec"; ...
                                   "AccelerometerStatic_axisZ_ps_spec"; ...                         
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                       ];


        datastore.SelectedVariables = ["Label"; ...
                                   "AccelerometerMoving_axisY"; ...
                                   "AccelerometerMoving_axisZ"; ...
                                   "AccelerometerStatic_axisY"; ...
                                   "AccelerometerStatic_axisZ"; ...                         
                                   "AccelerometerMoving_axisY_ps"; ...
                                   "AccelerometerMoving_axisZ_ps"; ...
                                   "AccelerometerStatic_axisY_ps"; ...
                                   "AccelerometerStatic_axisZ_ps"; ...                         
                                   "AccelerometerMoving_axisY_stats"; ...
                                   "AccelerometerMoving_axisZ_stats"; ...
                                   "AccelerometerStatic_axisY_stats"; ...
                                   "AccelerometerStatic_axisZ_stats"; ...                         
                                   "AccelerometerMoving_axisY_ps_spec"; ...
                                   "AccelerometerMoving_axisZ_ps_spec"; ...
                                   "AccelerometerStatic_axisY_ps_spec"; ...
                                   "AccelerometerStatic_axisZ_ps_spec"; ...                         
                                        ];


    else
        disp("Add parameter flag = signals, features, both, featuretable \n return datastore, but if featuretable is set return will be featuretable");
    end

    datastore.IndependentVariables = [
                                    "ThrottleValve1"; ...
                                    "ThrottleValve2"; ...
                                    "SmallDamper_upper"; ...
                                    "LargeDamper_upper"; ...
                                    "SmallDamper_bottom"; ...
                                    "LargeDamper_bottom";
                                    "Settings.Load"];
end

