function y = preprocess_AirPressure(x,tx)
%  Preprocess input x
%    This function expects an input vector x and a vector of time values
%    tx. tx is a numeric vector in units of seconds.
%    Follow the timetable documentation (type 'doc timetable' in
%    command line) to learn how to index into a table variable and its time
%    values so that you can pass them into this function.

% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 05-Apr-2021 19:14:41
x = x - mean(x);
y = smoothdata(x,'movmean',0.05,'SamplePoints',tx);
Fs = 1/mean(diff(tx)); % Average sample rate
y = lowpass(y,60,Fs,'Steepness',0.85,'StopbandAttenuation',60);
