function [trainedClassifier, validationAccuracy] = train_flow_pca(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double containing the accuracy in percent. In
%       the app, the History list displays this overall accuracy score for
%       each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   yfit = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 19-May-2021 18:14:23


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'FlowContraction_stats/ClearanceFactor', 'FlowContraction_stats/CrestFactor', 'FlowContraction_stats/ImpulseFactor', 'FlowContraction_stats/Kurtosis', 'FlowContraction_stats/Mean', 'FlowContraction_stats/PeakValue', 'FlowContraction_stats/RMS', 'FlowContraction_stats/SINAD', 'FlowContraction_stats/SNR', 'FlowContraction_stats/ShapeFactor', 'FlowContraction_stats/Skewness', 'FlowContraction_stats/Std', 'FlowContraction_stats/THD', 'FlowContraction_ps_spec/PeakAmp1', 'FlowContraction_ps_spec/PeakAmp2', 'FlowContraction_ps_spec/PeakAmp3', 'FlowContraction_ps_spec/PeakAmp4', 'FlowContraction_ps_spec/PeakAmp5', 'FlowContraction_ps_spec/PeakFreq1', 'FlowContraction_ps_spec/PeakFreq2', 'FlowContraction_ps_spec/PeakFreq3', 'FlowContraction_ps_spec/PeakFreq4', 'FlowContraction_ps_spec/PeakFreq5', 'FlowContraction_ps_spec/BandPower'};
predictors = inputTable(:, predictorNames);
response = inputTable.Label;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Apply a PCA to the predictor matrix.
% Run PCA on numeric predictors only. Categorical predictors are passed through PCA untouched.
isCategoricalPredictorBeforePCA = isCategoricalPredictor;
numericPredictors = predictors(:, ~isCategoricalPredictor);
numericPredictors = table2array(varfun(@double, numericPredictors));
% 'inf' values have to be treated as missing data for PCA.
numericPredictors(isinf(numericPredictors)) = NaN;
[pcaCoefficients, pcaScores, ~, ~, explained, pcaCenters] = pca(...
    numericPredictors);
% Keep enough components to explain the desired amount of variance.
explainedVarianceToKeepAsFraction = 98/100;
numComponentsToKeep = find(cumsum(explained)/sum(explained) >= explainedVarianceToKeepAsFraction, 1);
pcaCoefficients = pcaCoefficients(:,1:numComponentsToKeep);
predictors = [array2table(pcaScores(:,1:numComponentsToKeep)), predictors(:, isCategoricalPredictor)];
isCategoricalPredictor = [false(1,numComponentsToKeep), true(1,sum(isCategoricalPredictor))];

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
template = templateTree(...
    'MaxNumSplits', 3387);
classificationEnsemble = fitcensemble(...
    predictors, ...
    response, ...
    'Method', 'Bag', ...
    'NumLearningCycles', 30, ...
    'Learners', template, ...
    'ClassNames', {'damp_small_bot'; 'damp_small_bot+damp_small_up'; 'damp_small_bot+damps_large'; 'damp_small_up'; 'damps_large+damp_small_up'; 'health'; 'pressure+damp_small_bot'; 'pressure+damp_small_up'; 'pressure+damps_large'; 'pressure+valve1'; 'pressure+valve2'; 'valve1'; 'valve1+damp_small_bot'; 'valve1+damp_small_up'; 'valve1+damps_large'; 'valve1+valve2'; 'valve2'; 'valve2+damp_small_bot'; 'valve2+damp_small_up'; 'valve2+damps_large'});

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
pcaTransformationFcn = @(x) [ array2table((table2array(varfun(@double, x(:, ~isCategoricalPredictorBeforePCA))) - pcaCenters) * pcaCoefficients), x(:,isCategoricalPredictorBeforePCA) ];
ensemblePredictFcn = @(x) predict(classificationEnsemble, x);
trainedClassifier.predictFcn = @(x) ensemblePredictFcn(pcaTransformationFcn(predictorExtractionFcn(x)));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'FlowContraction_ps_spec/BandPower', 'FlowContraction_ps_spec/PeakAmp1', 'FlowContraction_ps_spec/PeakAmp2', 'FlowContraction_ps_spec/PeakAmp3', 'FlowContraction_ps_spec/PeakAmp4', 'FlowContraction_ps_spec/PeakAmp5', 'FlowContraction_ps_spec/PeakFreq1', 'FlowContraction_ps_spec/PeakFreq2', 'FlowContraction_ps_spec/PeakFreq3', 'FlowContraction_ps_spec/PeakFreq4', 'FlowContraction_ps_spec/PeakFreq5', 'FlowContraction_stats/ClearanceFactor', 'FlowContraction_stats/CrestFactor', 'FlowContraction_stats/ImpulseFactor', 'FlowContraction_stats/Kurtosis', 'FlowContraction_stats/Mean', 'FlowContraction_stats/PeakValue', 'FlowContraction_stats/RMS', 'FlowContraction_stats/SINAD', 'FlowContraction_stats/SNR', 'FlowContraction_stats/ShapeFactor', 'FlowContraction_stats/Skewness', 'FlowContraction_stats/Std', 'FlowContraction_stats/THD'};
trainedClassifier.PCACenters = pcaCenters;
trainedClassifier.PCACoefficients = pcaCoefficients;
trainedClassifier.ClassificationEnsemble = classificationEnsemble;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2021a.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'FlowContraction_stats/ClearanceFactor', 'FlowContraction_stats/CrestFactor', 'FlowContraction_stats/ImpulseFactor', 'FlowContraction_stats/Kurtosis', 'FlowContraction_stats/Mean', 'FlowContraction_stats/PeakValue', 'FlowContraction_stats/RMS', 'FlowContraction_stats/SINAD', 'FlowContraction_stats/SNR', 'FlowContraction_stats/ShapeFactor', 'FlowContraction_stats/Skewness', 'FlowContraction_stats/Std', 'FlowContraction_stats/THD', 'FlowContraction_ps_spec/PeakAmp1', 'FlowContraction_ps_spec/PeakAmp2', 'FlowContraction_ps_spec/PeakAmp3', 'FlowContraction_ps_spec/PeakAmp4', 'FlowContraction_ps_spec/PeakAmp5', 'FlowContraction_ps_spec/PeakFreq1', 'FlowContraction_ps_spec/PeakFreq2', 'FlowContraction_ps_spec/PeakFreq3', 'FlowContraction_ps_spec/PeakFreq4', 'FlowContraction_ps_spec/PeakFreq5', 'FlowContraction_ps_spec/BandPower'};
predictors = inputTable(:, predictorNames);
response = inputTable.Label;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Perform cross-validation
KFolds = 5;
cvp = cvpartition(response, 'KFold', KFolds);
% Initialize the predictions to the proper sizes
validationPredictions = response;
numObservations = size(predictors, 1);
numClasses = 20;
validationScores = NaN(numObservations, numClasses);
for fold = 1:KFolds
    trainingPredictors = predictors(cvp.training(fold), :);
    trainingResponse = response(cvp.training(fold), :);
    foldIsCategoricalPredictor = isCategoricalPredictor;
    
    % Apply a PCA to the predictor matrix.
    % Run PCA on numeric predictors only. Categorical predictors are passed through PCA untouched.
    isCategoricalPredictorBeforePCA = foldIsCategoricalPredictor;
    numericPredictors = trainingPredictors(:, ~foldIsCategoricalPredictor);
    numericPredictors = table2array(varfun(@double, numericPredictors));
    % 'inf' values have to be treated as missing data for PCA.
    numericPredictors(isinf(numericPredictors)) = NaN;
    [pcaCoefficients, pcaScores, ~, ~, explained, pcaCenters] = pca(...
        numericPredictors);
    % Keep enough components to explain the desired amount of variance.
    explainedVarianceToKeepAsFraction = 98/100;
    numComponentsToKeep = find(cumsum(explained)/sum(explained) >= explainedVarianceToKeepAsFraction, 1);
    pcaCoefficients = pcaCoefficients(:,1:numComponentsToKeep);
    trainingPredictors = [array2table(pcaScores(:,1:numComponentsToKeep)), trainingPredictors(:, foldIsCategoricalPredictor)];
    foldIsCategoricalPredictor = [false(1,numComponentsToKeep), true(1,sum(foldIsCategoricalPredictor))];
    
    % Train a classifier
    % This code specifies all the classifier options and trains the classifier.
    template = templateTree(...
        'MaxNumSplits', 3387);
    classificationEnsemble = fitcensemble(...
        trainingPredictors, ...
        trainingResponse, ...
        'Method', 'Bag', ...
        'NumLearningCycles', 30, ...
        'Learners', template, ...
        'ClassNames', {'damp_small_bot'; 'damp_small_bot+damp_small_up'; 'damp_small_bot+damps_large'; 'damp_small_up'; 'damps_large+damp_small_up'; 'health'; 'pressure+damp_small_bot'; 'pressure+damp_small_up'; 'pressure+damps_large'; 'pressure+valve1'; 'pressure+valve2'; 'valve1'; 'valve1+damp_small_bot'; 'valve1+damp_small_up'; 'valve1+damps_large'; 'valve1+valve2'; 'valve2'; 'valve2+damp_small_bot'; 'valve2+damp_small_up'; 'valve2+damps_large'});
    
    % Create the result struct with predict function
    pcaTransformationFcn = @(x) [ array2table((table2array(varfun(@double, x(:, ~isCategoricalPredictorBeforePCA))) - pcaCenters) * pcaCoefficients), x(:,isCategoricalPredictorBeforePCA) ];
    ensemblePredictFcn = @(x) predict(classificationEnsemble, x);
    validationPredictFcn = @(x) ensemblePredictFcn(pcaTransformationFcn(x));
    
    % Add additional fields to the result struct
    
    % Compute validation predictions
    validationPredictors = predictors(cvp.test(fold), :);
    [foldPredictions, foldScores] = validationPredictFcn(validationPredictors);
    
    % Store predictions in the original order
    validationPredictions(cvp.test(fold), :) = foldPredictions;
    validationScores(cvp.test(fold), :) = foldScores;
end

% Compute validation accuracy
correctPredictions = strcmp( strtrim(validationPredictions), strtrim(response));
isMissing = cellfun(@(x) all(isspace(x)), response, 'UniformOutput', true);
correctPredictions = correctPredictions(~isMissing);
validationAccuracy = sum(correctPredictions)/length(correctPredictions);
