%% import dataensemble
% Description:
% 	Processing esemble dataset add labels
% Content:
%	
%
% Author: Artyom Voronin
% Brno, 2021

disp("Starting")
addpath('../utils/');

path2data_converted = '../data/data11/*.mat';
loc_files = fullfile(path2data_converted);
ext_files = ".mat";

% Create and configure Ensemble datastore
datastore = fileEnsembleDatastore(loc_files, ext_files);

datastore.ReadFcn = @readData;
datastore.WriteToMemberFcn = @writeData;

datastore.DataVariables = [
                           "AccelerometerMoving_axisY"; ...
                           "AccelerometerMoving_axisZ"; ...
                           "AccelerometerStatic_axisY"; ...
                           "AccelerometerStatic_axisZ"; ...                         
                           "AccelerometerMoving_axisY_ps"; ...
                           "AccelerometerMoving_axisZ_ps"; ...
                           "AccelerometerStatic_axisY_ps"; ...
                           "AccelerometerStatic_axisZ_ps"; ...                         
                           "AccelerometerMoving_axisY_stats"; ...
                           "AccelerometerMoving_axisZ_stats"; ...
                           "AccelerometerStatic_axisY_stats"; ...
                           "AccelerometerStatic_axisZ_stats"; ...                         
                           "AccelerometerMoving_axisY_ps_spec"; ...
                           "AccelerometerMoving_axisZ_ps_spec"; ...
                           "AccelerometerStatic_axisY_ps_spec"; ...
                           "AccelerometerStatic_axisZ_ps_spec"; ...                         
                           ];

datastore.ConditionVariables = ["FaultCode"; ...
                                "Label"; ...
                                "ThrottleValve1"; ...
                                "ThrottleValve2"; ...
                                "SmallDamper_upper"; ...
                                "LargeDamper_upper"; ...
                                "SmallDamper_bottom"; ...
                                "LargeDamper_bottom";
                                "Settings.Load"];

datastore.IndependentVariables = ["Temp_Cylinder"; ...
                                  "Temp_Ambient"; ...
                                ];

datastore.SelectedVariables = ["Label"; ...
                           "AccelerometerMoving_axisY"; ...
                           "AccelerometerMoving_axisZ"; ...
                           "AccelerometerStatic_axisY"; ...
                           "AccelerometerStatic_axisZ"; ...                         
                           "AccelerometerMoving_axisY_ps"; ...
                           "AccelerometerMoving_axisZ_ps"; ...
                           "AccelerometerStatic_axisY_ps"; ...
                           "AccelerometerStatic_axisZ_ps"; ...                         
                           "AccelerometerMoving_axisY_stats"; ...
                           "AccelerometerMoving_axisZ_stats"; ...
                           "AccelerometerStatic_axisY_stats"; ...
                           "AccelerometerStatic_axisZ_stats"; ...                         
                           "AccelerometerMoving_axisY_ps_spec"; ...
                           "AccelerometerMoving_axisZ_ps_spec"; ...
                           "AccelerometerStatic_axisY_ps_spec"; ...
                           "AccelerometerStatic_axisZ_ps_spec"; ...                         
                                ];


clear loc_files ext_files path2data_converted
disp("Datastore import - done");
