%% import dataensemble
% Description:
% 	Processing esemble dataset add labels
% Content:
%	
%
% Author: Artyom Voronin
% Brno, 2021

disp("Starting")
addpath('../utils/');

path2data_converted = '../data/data11/*.mat';
loc_files = fullfile(path2data_converted);
ext_files = ".mat";

% Create and configure Ensemble datastore
datastore = fileEnsembleDatastore(loc_files, ext_files);

datastore.ReadFcn = @readData;
datastore.WriteToMemberFcn = @writeData;

datastore.DataVariables = ["MIC_uBumper"; ... 
                           "MIC_bBumper"; ...
                           "MIC_Ambient"; ... 
                           "MIC_uBumper_stats"; ... 
                           "MIC_bBumper_stats"; ...
                           "MIC_Ambient_stats"; ...
                           "MIC_uBumper_ps"; ... 
                           "MIC_bBumper_ps"; ...
                           "MIC_Ambient_ps"; ...
                           "MIC_uBumper_ps_spec_1"; ... 
                           "MIC_bBumper_ps_spec_1"; ... 
                           "MIC_Ambient_ps_spec_1"; ...
                           "outValveHP"; ... 
                           "outValveWP";...
                           ];

datastore.ConditionVariables = ["FaultCode"; ...
                                "Label"; ...
                                "ThrottleValve1"; ...
                                "ThrottleValve2"; ...
                                "SmallDamper_upper"; ...
                                "LargeDamper_upper"; ...
                                "SmallDamper_bottom"; ...
                                "LargeDamper_bottom";
                                "Settings.Load"];

datastore.IndependentVariables = ["Temp_Cylinder"; ...
                                  "Temp_Ambient"; ...
                                ];

datastore.SelectedVariables = ["Label"; ...
                               "MIC_uBumper"; ... 
                               "MIC_bBumper"; ...
                               "MIC_Ambient"; ... 
                               "MIC_uBumper_stats"; ... 
                               "MIC_bBumper_stats"; ...
                               "MIC_Ambient_stats"; ...
                               "MIC_uBumper_ps"; ... 
                               "MIC_bBumper_ps"; ...
                               "MIC_Ambient_ps"; ...
                               "MIC_uBumper_ps_spec_1"; ... 
                               "MIC_bBumper_ps_spec_1"; ... 
                               "MIC_Ambient_ps_spec_1"; ...
                                ];


clear loc_files ext_files path2data_converted
disp("Datastore import - done");



%% Predicti:

predict = 1;
if predict
    reset(datastore);
    member = read(datastore);

    A = member.MIC_Ambient_stats{1,1}.SINAD;
    B = member.MIC_bBumper_ps_spec_1{1,1}.BandPower;
    C = member.MIC_bBumper_ps_spec_1{1,1}.PeakFreq1;
    D = member.MIC_bBumper_stats{1,1}.Mean;
    E = member.MIC_uBumper_ps_spec_1{1,1}.PeakAmp5;
    T = [A;B;C;D;E];
    variables = {'MIC_Ambient_stats/SINAD', ...
                 'MIC_bBumper_ps_spec_1/BandPower', ...
                 'MIC_bBumper_ps_spec_1/PeakFreq1', ...
                 'MIC_bBumper_stats/Mean', ...
                 'MIC_uBumper_ps_spec_1/PeakAmp5'};

    tab = table(A,B,C,D,E, 'VariableNames', variables)

end
