%% import dataensemble
% Description:
% 	Processing esemble dataset add labels
% Content:
%	
%
% Author: Artyom Voronin
% Brno, 2021

disp("Starting")
addpath('../utils/');

path2data_converted = '../data/data11/*.mat';
loc_files = fullfile(path2data_converted);
ext_files = ".mat";

% Create and configure Ensemble datastore
datastore = fileEnsembleDatastore(loc_files, ext_files);

datastore.ReadFcn = @readData;
datastore.WriteToMemberFcn = @writeData;

datastore.DataVariables = [
                            "ProximitySensor_bottom"; ...
                            "ProximitySensor_upper"; ...
                            "ProximitySensor_bottom_stats"; ...
                            "ProximitySensor_upper_stats"; ...
                           ];

datastore.ConditionVariables = ["FaultCode"; ...
                                "Label"; ...
                                "ThrottleValve1"; ...
                                "ThrottleValve2"; ...
                                "SmallDamper_upper"; ...
                                "LargeDamper_upper"; ...
                                "SmallDamper_bottom"; ...
                                "LargeDamper_bottom";
                                "Settings.Load"];

datastore.IndependentVariables = ["Temp_Cylinder"; ...
                                  "Temp_Ambient"; ...
                                ];

datastore.SelectedVariables = ["Label"; ...
                               "ProximitySensor_bottom"; ...
                               "ProximitySensor_upper"; ...
                               "ProximitySensor_bottom_stats"; ...
                               "ProximitySensor_upper_stats"; ...
                                ];


clear loc_files ext_files path2data_converted
disp("Datastore import - done");
