function [featureTable,ranking,outputTable] = mics_features_process(inputData)
%DIAGNOSTICFEATURES recreates results in Diagnostic Feature Designer.
%
% Input:
%  inputData: A table or a cell array of tables/matrices containing the
%  data as those imported into the app.
%
% Output:
%  featureTable: A table containing all features and condition variables.
%  ranking: A table containing ranking scores for selected features.
%  outputTable: A table containing the computation results.
%
% This function computes features:
%  MIC_uBumper_stats/ClearanceFactor
%  MIC_uBumper_stats/CrestFactor
%  MIC_uBumper_stats/ImpulseFactor
%  MIC_uBumper_stats/Kurtosis
%  MIC_uBumper_stats/Mean
%  MIC_uBumper_stats/PeakValue
%  MIC_uBumper_stats/RMS
%  MIC_uBumper_stats/SINAD
%  MIC_uBumper_stats/SNR
%  MIC_uBumper_stats/ShapeFactor
%  MIC_uBumper_stats/Skewness
%  MIC_uBumper_stats/Std
%  MIC_uBumper_stats/THD
%  MIC_bBumper_stats/ClearanceFactor
%  MIC_bBumper_stats/CrestFactor
%  MIC_bBumper_stats/ImpulseFactor
%  MIC_bBumper_stats/Kurtosis
%  MIC_bBumper_stats/Mean
%  MIC_bBumper_stats/PeakValue
%  MIC_bBumper_stats/RMS
%  MIC_bBumper_stats/SINAD
%  MIC_bBumper_stats/SNR
%  MIC_bBumper_stats/ShapeFactor
%  MIC_bBumper_stats/Skewness
%  MIC_bBumper_stats/Std
%  MIC_bBumper_stats/THD
%  MIC_Ambient_stats/ClearanceFactor
%  MIC_Ambient_stats/CrestFactor
%  MIC_Ambient_stats/ImpulseFactor
%  MIC_Ambient_stats/Kurtosis
%  MIC_Ambient_stats/Mean
%  MIC_Ambient_stats/PeakValue
%  MIC_Ambient_stats/RMS
%  MIC_Ambient_stats/SINAD
%  MIC_Ambient_stats/SNR
%  MIC_Ambient_stats/ShapeFactor
%  MIC_Ambient_stats/Skewness
%  MIC_Ambient_stats/Std
%  MIC_Ambient_stats/THD
%  MIC_uBumper_ps_spec/PeakAmp1
%  MIC_uBumper_ps_spec/PeakAmp2
%  MIC_uBumper_ps_spec/PeakAmp3
%  MIC_uBumper_ps_spec/PeakAmp4
%  MIC_uBumper_ps_spec/PeakAmp5
%  MIC_uBumper_ps_spec/PeakAmp6
%  MIC_uBumper_ps_spec/PeakAmp7
%  MIC_uBumper_ps_spec/PeakAmp8
%  MIC_uBumper_ps_spec/PeakAmp9
%  MIC_uBumper_ps_spec/PeakAmp10
%  MIC_uBumper_ps_spec/PeakFreq1
%  MIC_uBumper_ps_spec/PeakFreq2
%  MIC_uBumper_ps_spec/PeakFreq3
%  MIC_uBumper_ps_spec/PeakFreq4
%  MIC_uBumper_ps_spec/PeakFreq5
%  MIC_uBumper_ps_spec/PeakFreq6
%  MIC_uBumper_ps_spec/PeakFreq7
%  MIC_uBumper_ps_spec/PeakFreq8
%  MIC_uBumper_ps_spec/PeakFreq9
%  MIC_uBumper_ps_spec/PeakFreq10
%  MIC_uBumper_ps_spec/BandPower
%  MIC_bBumper_ps_spec/PeakAmp1
%  MIC_bBumper_ps_spec/PeakAmp2
%  MIC_bBumper_ps_spec/PeakAmp3
%  MIC_bBumper_ps_spec/PeakAmp4
%  MIC_bBumper_ps_spec/PeakAmp5
%  MIC_bBumper_ps_spec/PeakAmp6
%  MIC_bBumper_ps_spec/PeakAmp7
%  MIC_bBumper_ps_spec/PeakAmp8
%  MIC_bBumper_ps_spec/PeakAmp9
%  MIC_bBumper_ps_spec/PeakAmp10
%  MIC_bBumper_ps_spec/PeakFreq1
%  MIC_bBumper_ps_spec/PeakFreq2
%  MIC_bBumper_ps_spec/PeakFreq3
%  MIC_bBumper_ps_spec/PeakFreq4
%  MIC_bBumper_ps_spec/PeakFreq5
%  MIC_bBumper_ps_spec/PeakFreq6
%  MIC_bBumper_ps_spec/PeakFreq7
%  MIC_bBumper_ps_spec/PeakFreq8
%  MIC_bBumper_ps_spec/PeakFreq9
%  MIC_bBumper_ps_spec/PeakFreq10
%  MIC_bBumper_ps_spec/BandPower
%  MIC_Ambient_ps_spec/PeakAmp1
%  MIC_Ambient_ps_spec/PeakAmp2
%  MIC_Ambient_ps_spec/PeakAmp3
%  MIC_Ambient_ps_spec/PeakAmp4
%  MIC_Ambient_ps_spec/PeakAmp5
%  MIC_Ambient_ps_spec/PeakAmp6
%  MIC_Ambient_ps_spec/PeakAmp7
%  MIC_Ambient_ps_spec/PeakAmp8
%  MIC_Ambient_ps_spec/PeakAmp9
%  MIC_Ambient_ps_spec/PeakAmp10
%  MIC_Ambient_ps_spec/PeakFreq1
%  MIC_Ambient_ps_spec/PeakFreq2
%  MIC_Ambient_ps_spec/PeakFreq3
%  MIC_Ambient_ps_spec/PeakFreq4
%  MIC_Ambient_ps_spec/PeakFreq5
%  MIC_Ambient_ps_spec/PeakFreq6
%  MIC_Ambient_ps_spec/PeakFreq7
%  MIC_Ambient_ps_spec/PeakFreq8
%  MIC_Ambient_ps_spec/PeakFreq9
%  MIC_Ambient_ps_spec/PeakFreq10
%  MIC_Ambient_ps_spec/BandPower
%
% This function ranks computed feautres using algorithms:
%  Kruskal-Wallis
%
% Organization of the function:
% 1. Compute signals/spectra/features
% 2. Extract computed features into a table
% 3. Rank features
%
% Modify the function to add or remove data processing, feature generation
% or ranking operations.

% Auto-generated by MATLAB on 02-May-2021 23:05:21

% Create output ensemble.
outputEnsemble = workspaceEnsemble(inputData,'DataVariables',["MIC_uBumper_stats/ClearanceFactor";"MIC_uBumper_stats/CrestFactor";"MIC_uBumper_stats/ImpulseFactor";"MIC_uBumper_stats/Kurtosis";"MIC_uBumper_stats/Mean";"MIC_uBumper_stats/PeakValue";"MIC_uBumper_stats/RMS";"MIC_uBumper_stats/SINAD";"MIC_uBumper_stats/SNR";"MIC_uBumper_stats/ShapeFactor";"MIC_uBumper_stats/Skewness";"MIC_uBumper_stats/Std";"MIC_uBumper_stats/THD";"MIC_bBumper_stats/ClearanceFactor";"MIC_bBumper_stats/CrestFactor";"MIC_bBumper_stats/ImpulseFactor";"MIC_bBumper_stats/Kurtosis";"MIC_bBumper_stats/Mean";"MIC_bBumper_stats/PeakValue";"MIC_bBumper_stats/RMS";"MIC_bBumper_stats/SINAD";"MIC_bBumper_stats/SNR";"MIC_bBumper_stats/ShapeFactor";"MIC_bBumper_stats/Skewness";"MIC_bBumper_stats/Std";"MIC_bBumper_stats/THD";"MIC_Ambient_stats/ClearanceFactor";"MIC_Ambient_stats/CrestFactor";"MIC_Ambient_stats/ImpulseFactor";"MIC_Ambient_stats/Kurtosis";"MIC_Ambient_stats/Mean";"MIC_Ambient_stats/PeakValue";"MIC_Ambient_stats/RMS";"MIC_Ambient_stats/SINAD";"MIC_Ambient_stats/SNR";"MIC_Ambient_stats/ShapeFactor";"MIC_Ambient_stats/Skewness";"MIC_Ambient_stats/Std";"MIC_Ambient_stats/THD";"MIC_uBumper_ps_spec/PeakAmp1";"MIC_uBumper_ps_spec/PeakAmp2";"MIC_uBumper_ps_spec/PeakAmp3";"MIC_uBumper_ps_spec/PeakAmp4";"MIC_uBumper_ps_spec/PeakAmp5";"MIC_uBumper_ps_spec/PeakAmp6";"MIC_uBumper_ps_spec/PeakAmp7";"MIC_uBumper_ps_spec/PeakAmp8";"MIC_uBumper_ps_spec/PeakAmp9";"MIC_uBumper_ps_spec/PeakAmp10";"MIC_uBumper_ps_spec/PeakFreq1";"MIC_uBumper_ps_spec/PeakFreq2";"MIC_uBumper_ps_spec/PeakFreq3";"MIC_uBumper_ps_spec/PeakFreq4";"MIC_uBumper_ps_spec/PeakFreq5";"MIC_uBumper_ps_spec/PeakFreq6";"MIC_uBumper_ps_spec/PeakFreq7";"MIC_uBumper_ps_spec/PeakFreq8";"MIC_uBumper_ps_spec/PeakFreq9";"MIC_uBumper_ps_spec/PeakFreq10";"MIC_uBumper_ps_spec/BandPower";"MIC_bBumper_ps_spec/PeakAmp1";"MIC_bBumper_ps_spec/PeakAmp2";"MIC_bBumper_ps_spec/PeakAmp3";"MIC_bBumper_ps_spec/PeakAmp4";"MIC_bBumper_ps_spec/PeakAmp5";"MIC_bBumper_ps_spec/PeakAmp6";"MIC_bBumper_ps_spec/PeakAmp7";"MIC_bBumper_ps_spec/PeakAmp8";"MIC_bBumper_ps_spec/PeakAmp9";"MIC_bBumper_ps_spec/PeakAmp10";"MIC_bBumper_ps_spec/PeakFreq1";"MIC_bBumper_ps_spec/PeakFreq2";"MIC_bBumper_ps_spec/PeakFreq3";"MIC_bBumper_ps_spec/PeakFreq4";"MIC_bBumper_ps_spec/PeakFreq5";"MIC_bBumper_ps_spec/PeakFreq6";"MIC_bBumper_ps_spec/PeakFreq7";"MIC_bBumper_ps_spec/PeakFreq8";"MIC_bBumper_ps_spec/PeakFreq9";"MIC_bBumper_ps_spec/PeakFreq10";"MIC_bBumper_ps_spec/BandPower";"MIC_Ambient_ps_spec/PeakAmp1";"MIC_Ambient_ps_spec/PeakAmp2";"MIC_Ambient_ps_spec/PeakAmp3";"MIC_Ambient_ps_spec/PeakAmp4";"MIC_Ambient_ps_spec/PeakAmp5";"MIC_Ambient_ps_spec/PeakAmp6";"MIC_Ambient_ps_spec/PeakAmp7";"MIC_Ambient_ps_spec/PeakAmp8";"MIC_Ambient_ps_spec/PeakAmp9";"MIC_Ambient_ps_spec/PeakAmp10";"MIC_Ambient_ps_spec/PeakFreq1";"MIC_Ambient_ps_spec/PeakFreq2";"MIC_Ambient_ps_spec/PeakFreq3";"MIC_Ambient_ps_spec/PeakFreq4";"MIC_Ambient_ps_spec/PeakFreq5";"MIC_Ambient_ps_spec/PeakFreq6";"MIC_Ambient_ps_spec/PeakFreq7";"MIC_Ambient_ps_spec/PeakFreq8";"MIC_Ambient_ps_spec/PeakFreq9";"MIC_Ambient_ps_spec/PeakFreq10";"MIC_Ambient_ps_spec/BandPower"],'ConditionVariables',"Label");


% Gather all features into a table.
featureTable = readFeatureTable(outputEnsemble);

% Feature ranking for FeatureTable1
selectedFeatureNames = ["MIC_uBumper_stats/ClearanceFactor","MIC_uBumper_stats/CrestFactor","MIC_uBumper_stats/ImpulseFactor","MIC_uBumper_stats/Kurtosis","MIC_uBumper_stats/Mean","MIC_uBumper_stats/PeakValue","MIC_uBumper_stats/RMS","MIC_uBumper_stats/SINAD","MIC_uBumper_stats/SNR","MIC_uBumper_stats/ShapeFactor","MIC_uBumper_stats/Skewness","MIC_uBumper_stats/Std","MIC_uBumper_stats/THD","MIC_bBumper_stats/ClearanceFactor","MIC_bBumper_stats/CrestFactor","MIC_bBumper_stats/ImpulseFactor","MIC_bBumper_stats/Kurtosis","MIC_bBumper_stats/Mean","MIC_bBumper_stats/PeakValue","MIC_bBumper_stats/RMS","MIC_bBumper_stats/SINAD","MIC_bBumper_stats/SNR","MIC_bBumper_stats/ShapeFactor","MIC_bBumper_stats/Skewness","MIC_bBumper_stats/Std","MIC_bBumper_stats/THD","MIC_Ambient_stats/ClearanceFactor","MIC_Ambient_stats/CrestFactor","MIC_Ambient_stats/ImpulseFactor","MIC_Ambient_stats/Kurtosis","MIC_Ambient_stats/Mean","MIC_Ambient_stats/PeakValue","MIC_Ambient_stats/RMS","MIC_Ambient_stats/SINAD","MIC_Ambient_stats/SNR","MIC_Ambient_stats/ShapeFactor","MIC_Ambient_stats/Skewness","MIC_Ambient_stats/Std","MIC_Ambient_stats/THD","MIC_uBumper_ps_spec/PeakAmp1","MIC_uBumper_ps_spec/PeakAmp2","MIC_uBumper_ps_spec/PeakAmp3","MIC_uBumper_ps_spec/PeakAmp4","MIC_uBumper_ps_spec/PeakAmp5","MIC_uBumper_ps_spec/PeakAmp6","MIC_uBumper_ps_spec/PeakAmp7","MIC_uBumper_ps_spec/PeakAmp8","MIC_uBumper_ps_spec/PeakAmp9","MIC_uBumper_ps_spec/PeakAmp10","MIC_uBumper_ps_spec/PeakFreq1","MIC_uBumper_ps_spec/PeakFreq2","MIC_uBumper_ps_spec/PeakFreq3","MIC_uBumper_ps_spec/PeakFreq4","MIC_uBumper_ps_spec/PeakFreq5","MIC_uBumper_ps_spec/PeakFreq6","MIC_uBumper_ps_spec/PeakFreq7","MIC_uBumper_ps_spec/PeakFreq8","MIC_uBumper_ps_spec/PeakFreq9","MIC_uBumper_ps_spec/PeakFreq10","MIC_uBumper_ps_spec/BandPower","MIC_bBumper_ps_spec/PeakAmp1","MIC_bBumper_ps_spec/PeakAmp2","MIC_bBumper_ps_spec/PeakAmp3","MIC_bBumper_ps_spec/PeakAmp4","MIC_bBumper_ps_spec/PeakAmp5","MIC_bBumper_ps_spec/PeakAmp6","MIC_bBumper_ps_spec/PeakAmp7","MIC_bBumper_ps_spec/PeakAmp8","MIC_bBumper_ps_spec/PeakAmp9","MIC_bBumper_ps_spec/PeakAmp10","MIC_bBumper_ps_spec/PeakFreq1","MIC_bBumper_ps_spec/PeakFreq2","MIC_bBumper_ps_spec/PeakFreq3","MIC_bBumper_ps_spec/PeakFreq4","MIC_bBumper_ps_spec/PeakFreq5","MIC_bBumper_ps_spec/PeakFreq6","MIC_bBumper_ps_spec/PeakFreq7","MIC_bBumper_ps_spec/PeakFreq8","MIC_bBumper_ps_spec/PeakFreq9","MIC_bBumper_ps_spec/PeakFreq10","MIC_bBumper_ps_spec/BandPower","MIC_Ambient_ps_spec/PeakAmp1","MIC_Ambient_ps_spec/PeakAmp2","MIC_Ambient_ps_spec/PeakAmp3","MIC_Ambient_ps_spec/PeakAmp4","MIC_Ambient_ps_spec/PeakAmp5","MIC_Ambient_ps_spec/PeakAmp6","MIC_Ambient_ps_spec/PeakAmp7","MIC_Ambient_ps_spec/PeakAmp8","MIC_Ambient_ps_spec/PeakAmp9","MIC_Ambient_ps_spec/PeakAmp10","MIC_Ambient_ps_spec/PeakFreq1","MIC_Ambient_ps_spec/PeakFreq2","MIC_Ambient_ps_spec/PeakFreq3","MIC_Ambient_ps_spec/PeakFreq4","MIC_Ambient_ps_spec/PeakFreq5","MIC_Ambient_ps_spec/PeakFreq6","MIC_Ambient_ps_spec/PeakFreq7","MIC_Ambient_ps_spec/PeakFreq8","MIC_Ambient_ps_spec/PeakFreq9","MIC_Ambient_ps_spec/PeakFreq10","MIC_Ambient_ps_spec/BandPower"];

% Get selected features and labels for classification ranking
selectedFeatureValues = featureTable{:,selectedFeatureNames};
label = featureTable{:,"Label"};

% Convert label to numeric values
if iscategorical(label)
    label = string(label);
end
group = grp2idx(label);

% Initialize an empty matrix to store ranking scores
score = zeros(numel(selectedFeatureNames),0);

% Initialize a string array to store ranking method names
methodList = strings(0);

%% Kruskal-Wallis
% Normalize features using minmax.
fNorm = (selectedFeatureValues-min(selectedFeatureValues,[],1))./(max(selectedFeatureValues,[],1)-min(selectedFeatureValues,[],1));

% Compute ranking score using Kruskal-Wallis.
numFeatures = size(fNorm,2);
z = zeros(numFeatures,1);
for k=1:numFeatures
    [~,tbl] = kruskalwallis(fNorm(:,k),group,'off');
    % Get test statistics from the Kruskal-Wallis test.
    stats = tbl{2,5};
    if ~isempty(stats)
        z(k) = stats;
    end
end

% Weight score by correlation importance.
z = correlationWeightedScore(fNorm,z,1);

% Append new score and method name.
score = [score,z];
methodList = [methodList,"Kruskal-Wallis"];


%% Create ranking result table
featureColumn = table(selectedFeatureNames(:),'VariableNames',{'Features'});
ranking = [featureColumn array2table(score,'VariableNames',methodList)];
ranking = sortrows(ranking,'Kruskal-Wallis','descend');

% Set SelectedVariables to select variables to read from the ensemble.
outputEnsemble.SelectedVariables = unique([outputEnsemble.DataVariables;outputEnsemble.ConditionVariables;outputEnsemble.IndependentVariables],'stable');

% Gather results into a table.
outputTable = readall(outputEnsemble);
end
