function [datastore] = sb_encoder(datastore, flag)
    if flag == "init"
        datastore.DataVariables = [
                                   "LeverPosition"; ...
                                   "LeverPosition_stats"; ...
                                   "LeverVelocity"; ...
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                        ];

        datastore.IndependentVariables = [
                                        "ThrottleValve1"; ...
                                        "ThrottleValve2"; ...
                                        "SmallDamper_upper"; ...
                                        "LargeDamper_upper"; ...
                                        "SmallDamper_bottom"; ...
                                        "LargeDamper_bottom";
                                        "Settings.Load"];

        datastore.SelectedVariables = ["Label"; ...
                                       "LeverPosition"; ...
                                       "LeverPosition_stats"; ...
                                       "LeverVelocity"; ...
                                        ];

    elseif flag == "signals"
        datastore.DataVariables = [
                                   "LeverPosition"; ...
                                   "LeverPosition_ps"; ...
                                   "LeverVelocity"; ...
                                   "LeverVelocity_ps"; ...
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                        ];

        datastore.IndependentVariables = [
                                        "ThrottleValve1"; ...
                                        "ThrottleValve2"; ...
                                        "SmallDamper_upper"; ...
                                        "LargeDamper_upper"; ...
                                        "SmallDamper_bottom"; ...
                                        "LargeDamper_bottom";
                                        "Settings.Load"];

        datastore.SelectedVariables = ["Label"; ...
                                       "LeverPosition"; ...
                                       "LeverPosition_ps"; ...
                                       "LeverVelocity"; ...
                                       "LeverVelocity_ps"; ...
                                        ];

    elseif flag == "features"
        datastore.DataVariables = [
                                   "LeverPosition_stats"; ...
                                   "LeverPosition_nonlin"; ...
                                   "LeverPosition_ps_spec"; ...
                                   "LeverVelocity_ps_spec"; ...
                                   "LeverVelocity_stats"; ...
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                        ];

        datastore.IndependentVariables = [
                                        "ThrottleValve1"; ...
                                        "ThrottleValve2"; ...
                                        "SmallDamper_upper"; ...
                                        "LargeDamper_upper"; ...
                                        "SmallDamper_bottom"; ...
                                        "LargeDamper_bottom";
                                        "Settings.Load"];

        datastore.SelectedVariables = ["Label"; ...
                                       "LeverPosition_stats"; ...
                                       "LeverPosition_nonlin"; ...
                                       "LeverPosition_ps_spec"; ...
                                       "LeverVelocity_ps_spec"; ...
                                       "LeverVelocity_stats"; ...
                                        ];

    elseif flag == "featuretable"
        featuretable = load('encoder_features.mat');
        datastore = featuretable;

    elseif flag == "both"
        datastore.DataVariables = [
                                   "LeverPosition"; ...
                                   "LeverPosition_stats"; ...
                                   "LeverPosition_nonlin"; ...
                                   "LeverPosition_ps"; ...
                                   "LeverPosition_ps_spec"; ...
                                   "LeverVelocity"; ...
                                   "LeverVelocity_ps"; ...
                                   "LeverVelocity_ps_spec"; ...
                                   "LeverVelocity_stats"; ...
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                        ];

        datastore.IndependentVariables = [
                                        "ThrottleValve1"; ...
                                        "ThrottleValve2"; ...
                                        "SmallDamper_upper"; ...
                                        "LargeDamper_upper"; ...
                                        "SmallDamper_bottom"; ...
                                        "LargeDamper_bottom";
                                        "Settings.Load"];

        datastore.SelectedVariables = ["Label"; ...
                                       "LeverPosition"; ...
                                       "LeverPosition_stats"; ...
                                       "LeverPosition_nonlin"; ...
                                       "LeverPosition_ps"; ...
                                       "LeverPosition_ps_spec"; ...
                                       "LeverVelocity"; ...
                                       "LeverVelocity_ps"; ...
                                       "LeverVelocity_ps_spec"; ...
                                       "LeverVelocity_stats"; ...
                                        ];

    else
        disp("Add parameter flag = signals, features, both, featuretable \n return datastore, but if featuretable is set return will be featuretable");
    end

end




















