function [datastore] = sb_strain(datastore, flag)
    if flag == "init"
        datastore.DataVariables = [
                                    "StrainGauge"; ...
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                        ];


        datastore.SelectedVariables = ["Label"; ...
                                       "StrainGauge"; ...
                                        ];


    if flag == "signals"
        datastore.DataVariables = [
                                    "StrainGauge"; ...
                                    "StrainGauge_ps"; ...
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                        ];


        datastore.SelectedVariables = ["Label"; ...
                                       "StrainGauge"; ...
                                       "StrainGauge_ps"; ...
                                        ];

    elseif flag == "features"
        datastore.DataVariables = [
                                    "StrainGauge_stats"; ...
                                    "StrainGauge_ps_spec"; ...
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                        ];


        datastore.SelectedVariables = ["Label"; ...
                                       "StrainGauge_stats"; ...
                                       "StrainGauge_ps_spec"; ...
                                        ];

    elseif flag == "featuretable"
        featuretable = load('strain_features.mat');
        datastore = featuretable;

    elseif flag == "both"
        datastore.DataVariables = [
                                    "StrainGauge"; ...
                                    "StrainGauge_stats"; ...
                                    "StrainGauge_ps"; ...
                                    "StrainGauge_ps_spec"; ...
                                   ];

        datastore.ConditionVariables = ["FaultCode"; ...
                                        "Label"; ...
                                        ];


        datastore.SelectedVariables = ["Label"; ...
                                       "StrainGauge"; ...
                                       "StrainGauge_stats"; ...
                                       "StrainGauge_ps"; ...
                                       "StrainGauge_ps_spec"; ...
                                        ];

    else
        disp("Add parameter flag = signals, features, both, featuretable \n return datastore, but if featuretable is set return will be featuretable");
    end

    datastore.IndependentVariables = [
                                    "ThrottleValve1"; ...
                                    "ThrottleValve2"; ...
                                    "SmallDamper_upper"; ...
                                    "LargeDamper_upper"; ...
                                    "SmallDamper_bottom"; ...
                                    "LargeDamper_bottom";
                                    "Settings.Load"];
end 
